### ISSUE TITLE
Dependency `redis` left out

### ISSUE THREAD

**Issue by JordanPlayz158** [Jexactyl/documentation#4]
**Describe the bug**
In the documentation, you give a list and example of all required dependencies but forgot redis which causes `composer install --no-dev --optimize-autoloader` and subsequent commands to fail

**To Reproduce**
1. Follow the current documentation guide up to "Depdendency installation" (might want to also fix the spelling mistake)
2. Run the first command in that section and you will get the `Connection refused [tcp://localhost:6379]` error

**Expected behavior**
The command resolves fine saying the expected message of `Package manifest generated successfully.`

**Screenshots**

**Desktop (please complete the following information):**
N/A (not related to issue)

**Smartphone (please complete the following information):**
N/A (not related to issue)

**Additional context**

**Comment by camwhi-te** [comment]
Resolved in f035688dae2f11786a7aa9b6824887e542b967b3
