### ISSUE TITLE
mysql user defaults to 'pterodactyl' in database setup

### ISSUE THREAD

**Issue by TheRealGramdalf** [Jexactyl/documentation#8]
In the `php artisan p:environment:database` command, the default username is 'pterodactyl', whereas in the database setup, (`CREATE USER 'jexactyl'@'127.0.0.1' IDENTIFIED BY 'yourPassword';`) the default is jexactyl.

**Comment by ddfsdsfsdf** [comment]
Fixed with [#127](https://github.com/Jexactyl/Jexactyl/pull/127)
